//
// MediaPostsAPI.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

open class MediaPostsAPI {

    /**
     получить медиа новости с сайта кинопоиск
     
     - parameter page: (query) номер страницы (optional, default to 1)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: MediaPostsResponse
     */
    open class func apiV1MediaPostsGet(page: Int? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) async throws(ErrorResponse) -> MediaPostsResponse {
        return try await apiV1MediaPostsGetWithRequestBuilder(page: page, apiConfiguration: apiConfiguration).execute().body
    }

    /**
     получить медиа новости с сайта кинопоиск
     - GET /api/v1/media_posts
     - Одна страница может содержать до 20 элементов в items.
     - API Key:
       - type: apiKey X-API-KEY (HEADER)
       - name: ApiKeyAuth
     - parameter page: (query) номер страницы (optional, default to 1)
     - parameter apiConfiguration: The configuration for the http request.
     - returns: RequestBuilder<MediaPostsResponse> 
     */
    open class func apiV1MediaPostsGetWithRequestBuilder(page: Int? = nil, apiConfiguration: OpenAPIClientAPIConfiguration = OpenAPIClientAPIConfiguration.shared) -> RequestBuilder<MediaPostsResponse> {
        let localVariablePath = "/api/v1/media_posts"
        let localVariableURLString = apiConfiguration.basePath + localVariablePath
        let localVariableParameters: [String: any Sendable]? = nil

        var localVariableUrlComponents = URLComponents(string: localVariableURLString)
        localVariableUrlComponents?.queryItems = APIHelper.mapValuesToQueryItems([
            "page": (wrappedValue: page?.asParameter(codableHelper: apiConfiguration.codableHelper), isExplode: true),
        ])

        let localVariableNillableHeaders: [String: (any Sendable)?] = [
            :
        ]

        let localVariableHeaderParameters = APIHelper.rejectNilHeaders(localVariableNillableHeaders)

        let localVariableRequestBuilder: RequestBuilder<MediaPostsResponse>.Type = apiConfiguration.requestBuilderFactory.getBuilder()

        return localVariableRequestBuilder.init(method: "GET", URLString: (localVariableUrlComponents?.string ?? localVariableURLString), parameters: localVariableParameters, headers: localVariableHeaderParameters, requiresAuthentication: true, apiConfiguration: apiConfiguration)
    }
}
