//
// ApiKeyResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ApiKeyResponse: Sendable, Codable, Hashable {

    public enum AccountType: String, Sendable, Codable, CaseIterable {
        case free = "FREE"
        case extended = "EXTENDED"
        case unlimited = "UNLIMITED"
    }
    public var totalQuota: ApiKeyResponseTotalQuota
    public var dailyQuota: ApiKeyResponseDailyQuota
    public var accountType: AccountType

    public init(totalQuota: ApiKeyResponseTotalQuota, dailyQuota: ApiKeyResponseDailyQuota, accountType: AccountType) {
        self.totalQuota = totalQuota
        self.dailyQuota = dailyQuota
        self.accountType = accountType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case totalQuota
        case dailyQuota
        case accountType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(totalQuota, forKey: .totalQuota)
        try container.encode(dailyQuota, forKey: .dailyQuota)
        try container.encode(accountType, forKey: .accountType)
    }
}

