//
// BoxOffice.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct BoxOffice: Sendable, Codable, Hashable {

    public var type: String
    public var amount: Int
    public var currencyCode: String
    public var name: String
    public var symbol: String

    public init(type: String, amount: Int, currencyCode: String, name: String, symbol: String) {
        self.type = type
        self.amount = amount
        self.currencyCode = currencyCode
        self.name = name
        self.symbol = symbol
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case type
        case amount
        case currencyCode
        case name
        case symbol
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(type, forKey: .type)
        try container.encode(amount, forKey: .amount)
        try container.encode(currencyCode, forKey: .currencyCode)
        try container.encode(name, forKey: .name)
        try container.encode(symbol, forKey: .symbol)
    }
}

