//
// DigitalReleaseResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct DigitalReleaseResponse: Sendable, Codable, Hashable {

    public var page: Int
    public var total: Int
    public var releases: [DigitalReleaseItem]

    public init(page: Int, total: Int, releases: [DigitalReleaseItem]) {
        self.page = page
        self.total = total
        self.releases = releases
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case page
        case total
        case releases
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(page, forKey: .page)
        try container.encode(total, forKey: .total)
        try container.encode(releases, forKey: .releases)
    }
}

