//
// Episode.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Episode: Sendable, Codable, Hashable {

    public var seasonNumber: Int
    public var episodeNumber: Int
    public var nameRu: String?
    public var nameEn: String?
    public var synopsis: String?
    public var releaseDate: String?

    public init(seasonNumber: Int, episodeNumber: Int, nameRu: String?, nameEn: String?, synopsis: String?, releaseDate: String?) {
        self.seasonNumber = seasonNumber
        self.episodeNumber = episodeNumber
        self.nameRu = nameRu
        self.nameEn = nameEn
        self.synopsis = synopsis
        self.releaseDate = releaseDate
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case seasonNumber
        case episodeNumber
        case nameRu
        case nameEn
        case synopsis
        case releaseDate
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(seasonNumber, forKey: .seasonNumber)
        try container.encode(episodeNumber, forKey: .episodeNumber)
        try container.encode(nameRu, forKey: .nameRu)
        try container.encode(nameEn, forKey: .nameEn)
        try container.encode(synopsis, forKey: .synopsis)
        try container.encode(releaseDate, forKey: .releaseDate)
    }
}

