//
// Fact.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Fact: Sendable, Codable, Hashable {

    public enum ModelType: String, Sendable, Codable, CaseIterable {
        case fact = "FACT"
        case blooper = "BLOOPER"
    }
    public var text: String
    public var type: ModelType
    public var spoiler: Bool

    public init(text: String, type: ModelType, spoiler: Bool) {
        self.text = text
        self.type = type
        self.spoiler = spoiler
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case text
        case type
        case spoiler
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(text, forKey: .text)
        try container.encode(type, forKey: .type)
        try container.encode(spoiler, forKey: .spoiler)
    }
}

