//
// FilmSearchResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FilmSearchResponse: Sendable, Codable, Hashable {
    public var keyword: String
    public var pagesCount: Int
    public var searchFilmsCountResult: Int
    public var films: [FilmSearchResponseFilms]

    public init(keyword: String, pagesCount: Int, searchFilmsCountResult: Int, films: [FilmSearchResponseFilms]) {
        self.keyword = keyword
        self.pagesCount = pagesCount
        self.searchFilmsCountResult = searchFilmsCountResult
        self.films = films
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case keyword
        case pagesCount
        case searchFilmsCountResult
        case films
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(keyword, forKey: .keyword)
        try container.encode(pagesCount, forKey: .pagesCount)
        try container.encode(searchFilmsCountResult, forKey: .searchFilmsCountResult)
        try container.encode(films, forKey: .films)
    }
}

