//
// FiltersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FiltersResponse: Sendable, Codable, Hashable {

    public var genres: [FiltersResponseGenres]
    public var countries: [FiltersResponseCountries]

    public init(genres: [FiltersResponseGenres], countries: [FiltersResponseCountries]) {
        self.genres = genres
        self.countries = countries
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case genres
        case countries
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(genres, forKey: .genres)
        try container.encode(countries, forKey: .countries)
    }
}

