//
// FiltersResponseCountries.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FiltersResponseCountries: Sendable, Codable, Hashable {

    public var id: Int?
    public var country: String?

    public init(id: Int? = nil, country: String? = nil) {
        self.id = id
        self.country = country
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case country
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(country, forKey: .country)
    }
}


extension FiltersResponseCountries: Identifiable {}
