//
// Genre.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Genre: Sendable, Codable, Hashable {

    public var genre: String

    public init(genre: String) {
        self.genre = genre
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case genre
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(genre, forKey: .genre)
    }
}

