//
// MediaPostsResponseItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct MediaPostsResponseItems: Sendable, Codable, Hashable {

    public var kinopoiskId: Int?
    public var imageUrl: String?
    public var title: String?
    public var description: String?
    public var url: String?
    public var publishedAt: String?

    public init(kinopoiskId: Int? = nil, imageUrl: String? = nil, title: String? = nil, description: String? = nil, url: String? = nil, publishedAt: String? = nil) {
        self.kinopoiskId = kinopoiskId
        self.imageUrl = imageUrl
        self.title = title
        self.description = description
        self.url = url
        self.publishedAt = publishedAt
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kinopoiskId
        case imageUrl
        case title
        case description
        case url
        case publishedAt
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(kinopoiskId, forKey: .kinopoiskId)
        try container.encodeIfPresent(imageUrl, forKey: .imageUrl)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(publishedAt, forKey: .publishedAt)
    }
}

