//
// RelatedFilmResponseItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct RelatedFilmResponseItems: Sendable, Codable, Hashable {

    public enum RelationType: String, Sendable, Codable, CaseIterable {
        case sequel = "SEQUEL"
        case prequel = "PREQUEL"
        case remake = "REMAKE"
        case similar = "SIMILAR"
        case version = "VERSION"
        case spoofs = "SPOOFS"
        case spoofed = "SPOOFED"
        case spinOff = "SPIN_OFF"
        case spunOffFrom = "SPUN_OFF_FROM"
        case references = "REFERENCES"
        case referencesIn = "REFERENCES_IN"
        case editedFrom = "EDITED_FROM"
        case editedInto = "EDITED_INTO"
        case alternateLanguage = "ALTERNATE_LANGUAGE"
    }
    public var kinopoiskId: Int?
    public var nameRu: String?
    public var nameEn: String?
    public var nameOriginal: String?
    public var posterUrl: String?
    public var posterUrlPreview: String?
    public var relationType: RelationType?

    public init(kinopoiskId: Int? = nil, nameRu: String? = nil, nameEn: String? = nil, nameOriginal: String? = nil, posterUrl: String? = nil, posterUrlPreview: String? = nil, relationType: RelationType? = nil) {
        self.kinopoiskId = kinopoiskId
        self.nameRu = nameRu
        self.nameEn = nameEn
        self.nameOriginal = nameOriginal
        self.posterUrl = posterUrl
        self.posterUrlPreview = posterUrlPreview
        self.relationType = relationType
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case kinopoiskId
        case nameRu
        case nameEn
        case nameOriginal
        case posterUrl
        case posterUrlPreview
        case relationType
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(kinopoiskId, forKey: .kinopoiskId)
        try container.encodeIfPresent(nameRu, forKey: .nameRu)
        try container.encodeIfPresent(nameEn, forKey: .nameEn)
        try container.encodeIfPresent(nameOriginal, forKey: .nameOriginal)
        try container.encodeIfPresent(posterUrl, forKey: .posterUrl)
        try container.encodeIfPresent(posterUrlPreview, forKey: .posterUrlPreview)
        try container.encodeIfPresent(relationType, forKey: .relationType)
    }
}

