//
// Season.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Season: Sendable, Codable, Hashable {

    public var number: Int
    public var episodes: [Episode]

    public init(number: Int, episodes: [Episode]) {
        self.number = number
        self.episodes = episodes
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case number
        case episodes
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(number, forKey: .number)
        try container.encode(episodes, forKey: .episodes)
    }
}

