//
// Country.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct Country: Sendable, Codable, Hashable {

    public var country: String

    public init(country: String) {
        self.country = country
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case country
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(country, forKey: .country)
    }
}

