//
// ExternalSourceResponseItems.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ExternalSourceResponseItems: Sendable, Codable, Hashable {

    public var url: String?
    public var platform: String?
    public var logoUrl: String?
    public var positiveRating: Int?
    public var negativeRating: Int?
    public var author: String?
    public var title: String?
    public var description: String?

    public init(url: String? = nil, platform: String? = nil, logoUrl: String? = nil, positiveRating: Int? = nil, negativeRating: Int? = nil, author: String? = nil, title: String? = nil, description: String? = nil) {
        self.url = url
        self.platform = platform
        self.logoUrl = logoUrl
        self.positiveRating = positiveRating
        self.negativeRating = negativeRating
        self.author = author
        self.title = title
        self.description = description
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case url
        case platform
        case logoUrl
        case positiveRating
        case negativeRating
        case author
        case title
        case description
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(url, forKey: .url)
        try container.encodeIfPresent(platform, forKey: .platform)
        try container.encodeIfPresent(logoUrl, forKey: .logoUrl)
        try container.encodeIfPresent(positiveRating, forKey: .positiveRating)
        try container.encodeIfPresent(negativeRating, forKey: .negativeRating)
        try container.encodeIfPresent(author, forKey: .author)
        try container.encodeIfPresent(title, forKey: .title)
        try container.encodeIfPresent(description, forKey: .description)
    }
}

