//
// FilmSearchByFiltersResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FilmSearchByFiltersResponse: Sendable, Codable, Hashable {

    public var total: Int
    public var totalPages: Int
    public var items: [FilmSearchByFiltersResponseItems]

    public init(total: Int, totalPages: Int, items: [FilmSearchByFiltersResponseItems]) {
        self.total = total
        self.totalPages = totalPages
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case totalPages
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encode(items, forKey: .items)
    }
}

