//
// FiltersResponseGenres.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct FiltersResponseGenres: Sendable, Codable, Hashable {

    public var id: Int?
    public var genre: String?

    public init(id: Int? = nil, genre: String? = nil) {
        self.id = id
        self.genre = genre
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case id
        case genre
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encodeIfPresent(id, forKey: .id)
        try container.encodeIfPresent(genre, forKey: .genre)
    }
}


extension FiltersResponseGenres: Identifiable {}
