//
// ReviewResponse.swift
//
// Generated by openapi-generator
// https://openapi-generator.tech
//

import Foundation

public struct ReviewResponse: Sendable, Codable, Hashable {

    /** Суммарное кол-во пользовательских рецензий */
    public var total: Int
    public var totalPages: Int
    public var totalPositiveReviews: Int
    public var totalNegativeReviews: Int
    public var totalNeutralReviews: Int
    public var items: [ReviewResponseItems]

    public init(total: Int, totalPages: Int, totalPositiveReviews: Int, totalNegativeReviews: Int, totalNeutralReviews: Int, items: [ReviewResponseItems]) {
        self.total = total
        self.totalPages = totalPages
        self.totalPositiveReviews = totalPositiveReviews
        self.totalNegativeReviews = totalNegativeReviews
        self.totalNeutralReviews = totalNeutralReviews
        self.items = items
    }

    public enum CodingKeys: String, CodingKey, CaseIterable {
        case total
        case totalPages
        case totalPositiveReviews
        case totalNegativeReviews
        case totalNeutralReviews
        case items
    }

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {
        var container = encoder.container(keyedBy: CodingKeys.self)
        try container.encode(total, forKey: .total)
        try container.encode(totalPages, forKey: .totalPages)
        try container.encode(totalPositiveReviews, forKey: .totalPositiveReviews)
        try container.encode(totalNegativeReviews, forKey: .totalNegativeReviews)
        try container.encode(totalNeutralReviews, forKey: .totalNeutralReviews)
        try container.encode(items, forKey: .items)
    }
}

